export default {
  TRANSACTION_SET_TRANSACTIONS: 'TRANSACTION_SET_TRANSACTIONS',
  TRANSACTION_SET_ISREFRESHING: 'TRANSACTION_SET_ISREFRESHING',

  IMPORTTRANS_SET_TRANSACTIONS: 'IMPORTTRANS_SET_TRANSACTIONS',
  IMPORTTRANS_SET_CHECKEDTRANSACTIONS: 'IMPORTTRANS_SET_CHECKEDTRANSACTIONS',
  IMPORTTRANS_SET_ALLCHECKED: 'IMPORTTRANS_SET_ALLCHECKED',
  IMPORTTRANS_SET_ISREFRESHING: 'IMPORTTRANS_SET_ISREFRESHING',

  CATEGORIES_SET_CATEGORIES: 'CATEGORIES_SET_CATEGORIES',

  ACCOUNTS_SET_ACCOUNTS: 'SET_ACCOUNTS',
  ACCOUNTS_SET_IMPORTED_ACCOUNTS: 'SET_IMPORTED_ACCOUNTS'
}
